// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxegotqerbmkmtflkgjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94ZWdvdHFlcmJta210ZmxrZ2p3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMzY1NDAsImV4cCI6MjA3ODcxMjU0MH0.uY18R-Cfq5teDPs6xqoQLzRkrh3e3YXTZRDhrnDa6SU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});